### PR TITLE
Create birthday_calculator

### PR DESCRIPTION
**Pull request by vinaya563**

### CODE REVIEW

**Comment by gohil-jay** [comment]
Hi, the guess you have followed the file structure this time! However, can you please change the folder name to 'Birthday Calculator' and change the name of the file to 'app.py' (as you have added non-python extension file in this PR).

**Comment by vinaya563** [comment]
Thanks for your valuable suggestions.I have done it as ayou have said.

**Comment by gohil-jay** [comment]
Hi, I see you have changed the file to proper name and extension. However, the folder or sub-repo name is still 'bthday calculator'. This, please change it to 'Birthday Calculator', and I'll merge the PR.

Thanks for contributing.

**Review by gohil-jay — CHANGES_REQUESTED** [review]
The files seem good to go, please check the sub-repo name once, after which it's good to get merged.

**Comment by vinaya563** [comment]
Hi, I have done it as said by you. Are there any other issues to be resolved..     !!!

**Review by gohil-jay — APPROVED** [review]
Alright, the structure is good to go!

**Pull request merged**
